-- return {
--   {
--     trig = "main",
--     name = "Main function",
--     dscr = "Python main function",
--     body = {
--       "def main():",
--       "    ${1:pass}",
--       "",
--       'if __name__ == "__main__":',
--       "    main()",
--     },
--   },
--   {
--     trig = "class",
--     name = "Python class",
--     dscr = "Create a Python class",
--     body = {
--       "class ${1:ClassName}:",
--       '    """${2:Class docstring}"""',
--       "",
--       "    def __init__(self, ${3:args}):",
--       '        """Initialize the class."""',
--       "        self.${4:attribute} = ${5:value}",
--       "",
--       "    def ${6:method_name}(self):",
--       '        """Method docstring."""',
--       "        return ${7:None}",
--     },
--   },
--   {
--     trig = "func",
--     name = "Function definition",
--     dscr = "Create a Python function",
--     body = {
--       "def ${1:function_name}(${2:params}):",
--       '    """${3:Function docstring}"""',
--       "    ${4:pass}",
--       "    return ${5:result}",
--     },
--   },
--   {
--     trig = "for",
--     name = "For loop",
--     dscr = "Create a for loop",
--     body = {
--       "for ${1:item} in ${2:items}:",
--       "    ${3:pass}",
--     },
--   },
--   {
--     trig = "try",
--     name = "Try/Except block",
--     dscr = "Create try/except block",
--     body = {
--       "try:",
--       "    ${1:code}",
--       "except ${2:Exception} as e:",
--       '    ${3:print(f"Error: {e}")}',
--     },
--   },
--   {
--     trig = "dataclass",
--     name = "Dataclass",
--     dscr = "Create a Python dataclass",
--     body = {
--       "@dataclass",
--       "class ${1:ClassName}:",
--       '    """${2:Class docstring}"""',
--       "    ${3:field1}: ${4:type}",
--       "    ${5:field2}: ${6:type} = ${7:default}",
--     },
--   },
-- }
