-- return {
--   {
--     trig = "inter",
--     name = "Interface",
--     dscr = "Create TypeScript interface",
--     body = {
--       "interface ${1:InterfaceName} {",
--       "  ${2:property}: ${3:type};",
--       "}",
--     },
--   },
--   {
--     trig = "type",
--     name = "Type alias",
--     dscr = "Create TypeScript type alias",
--     body = {
--       "type ${1:TypeName} = ${2:type};",
--     },
--   },
--   {
--     trig = "func",
--     name = "Typed function",
--     dscr = "TypeScript typed function",
--     body = {
--       "function ${1:name}(${2:param}: ${3:type}): ${4:returnType} {",
--       "  ${5:return ${6:value}}",
--       "}",
--     },
--   },
--   {
--     trig = "enum",
--     name = "Enum",
--     dscr = "Create TypeScript enum",
--     body = {
--       "enum ${1:EnumName} {",
--       '  ${2:Value1} = "${3:value1}",',
--       '  ${4:Value2} = "${5:value2}",',
--       "}",
--     },
--   },
-- }
