[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#000000"
background = "#cecece"

[colors.search.focused_match]
foreground = "#000000"
background = "#a4a4a4"

[colors.footer_bar]
foreground = "#000000"
background = "#ffffff"

[colors.selection]
text = "#000000"
background = "#ffffff"

[colors.normal]
black = "#000000"
red = "#a4a4a4"
green = "#b6b6b6"
yellow = "#cecece"
blue = "#8d8d8d"
magenta = "#9b9b9b"
cyan = "#b0b0b0"
white = "#ececec"

[colors.bright]
black = "#fdfdfd"
red = "#a4a4a4"
green = "#b6b6b6"
yellow = "#cecece"
blue = "#8d8d8d"
magenta = "#9b9b9b"
cyan = "#b0b0b0"
white = "#ffffff"
