foreground #ffffff
background #000000
selection_foreground #000000
selection_background #ffffff

cursor #ffffff
cursor_text_color #000000

active_border_color #8d8d8d
active_tab_background #8d8d8d

color0 #000000
color1 #a4a4a4
color2 #b6b6b6
color3 #cecece
color4 #8d8d8d
color5 #9b9b9b
color6 #b0b0b0
color7 #ececec
color8 #fdfdfd
color9 #a4a4a4
color10 #b6b6b6
color11 #cecece
color12 #8d8d8d
color13 #9b9b9b
color14 #b0b0b0
color15 #ffffff
