-- return {
--   {
--     trig = "af",
--     name = "Arrow function",
--     dscr = "JavaScript arrow function",
--     body = {
--       "const ${1:name} = (${2:params}) => {",
--       "  ${3:return ${4:value}}",
--       "};",
--     },
--   },
--   {
--     trig = "cl",
--     name = "Console log",
--     dscr = "JavaScript console.log",
--     body = {
--       "console.log(${1:value});",
--     },
--   },
--   {
--     trig = "for",
--     name = "For loop",
--     dscr = "JavaScript for loop",
--     body = {
--       "for (let ${1:i} = 0; ${1:i} < ${2:array}.length; ${1:i}++) {",
--       "  ${3:const ${4:item} = ${2:array}[${1:i}];}",
--       "}",
--     },
--   },
--   {
--     trig = "ife",
--     name = "If/Else",
--     dscr = "JavaScript if/else statement",
--     body = {
--       "if (${1:condition}) {",
--       "  ${2:code}",
--       "} else {",
--       "  ${3:code}",
--       "}",
--     },
--   },
-- }
