-- return {
--   {
--     trig = "obj",
--     name = "JSON object",
--     dscr = "Create an empty JSON object",
--     body = {
--       "{",
--       '  "${1:key}": "${2:value}"',
--       "}",
--     },
--   },
--   {
--     trig = "arr",
--     name = "JSON array",
--     dscr = "Create a JSON array",
--     body = {
--       "[",
--       '  "${1:item1}",',
--       '  "${2:item2}"',
--       "]",
--     },
--   },
-- }
