-- return {
--   {
--     trig = "code",
--     name = "Code block",
--     dscr = "Create a code block with language",
--     body = {
--       "```${1:python}",
--       "${2:code}",
--       "```",
--     },
--   },
--   {
--     trig = "img",
--     name = "Image",
--     dscr = "Insert an image",
--     body = {
--       "![${1:alt text}](${2:image-url})",
--     },
--   },
--   {
--     trig = "link",
--     name = "Link",
--     dscr = "Insert a link",
--     body = {
--       "[${1:text}](${2:url})",
--     },
--   },
--   {
--     trig = "table",
--     name = "Table",
--     dscr = "Create a markdown table",
--     body = {
--       "| ${1:Header 1} | ${2:Header 2} |",
--       "|--------------|--------------|",
--       "| ${3:Cell 1}   | ${4:Cell 2}   |",
--     },
--   },
-- }
