#!/bin/bash
# theme-set hook: recolor the Limine boot menu to match the active Omarchy theme.
# Installed via: omarchy hook install theme-set limine-theme-sync.sh
set -euo pipefail

COLORS_FILE="$HOME/.local/state/omarchy/current/theme/colors.toml"
LIMINE_CONF="/boot/limine.conf"

# /boot is typically not readable by an unprivileged user on this system, so
# a plain `[[ -f $LIMINE_CONF ]]` test as this user silently evaluates false
# even when the file exists — don't gate on it. The colors file lives under
# $HOME and is always readable, so that check alone is enough of a guard.
[[ -f $COLORS_FILE ]] || exit 0

get() {
  sed -n "s/^$1 = \"#\\([0-9a-fA-F]\\{6\\}\\)\"/\\1/p" "$COLORS_FILE" | head -n1
}

ACCENT=$(get accent)
BG=$(get background)
DARKER_BG=$(get darker_background)
LIGHTER_BG=$(get lighter_background)
FG=$(get foreground)
BRIGHT_FG=$(get bright_foreground)
LIGHT_FG=$(get light_foreground)

RED=$(get red); YELLOW=$(get yellow); GREEN=$(get green)
BLUE=$(get blue); MAGENTA=$(get magenta); CYAN=$(get cyan)

BRIGHT_RED=$(get bright_red); BRIGHT_YELLOW=$(get bright_yellow); BRIGHT_GREEN=$(get bright_green)
BRIGHT_BLUE=$(get bright_blue); BRIGHT_MAGENTA=$(get bright_magenta); BRIGHT_CYAN=$(get bright_cyan)

# Fall back to base color when a theme omits a bright_* variant.
BRIGHT_RED=${BRIGHT_RED:-$RED}; BRIGHT_YELLOW=${BRIGHT_YELLOW:-$YELLOW}; BRIGHT_GREEN=${BRIGHT_GREEN:-$GREEN}
BRIGHT_BLUE=${BRIGHT_BLUE:-$BLUE}; BRIGHT_MAGENTA=${BRIGHT_MAGENTA:-$MAGENTA}; BRIGHT_CYAN=${BRIGHT_CYAN:-$CYAN}
LIGHT_FG=${LIGHT_FG:-$FG}; BRIGHT_FG=${BRIGHT_FG:-$FG}
DARKER_BG=${DARKER_BG:-$BG}; LIGHTER_BG=${LIGHTER_BG:-$BG}

# Any required color missing (theme.toml malformed/incomplete) -> leave Limine alone.
for v in "$ACCENT" "$BG" "$FG" "$RED" "$YELLOW" "$GREEN" "$BLUE" "$MAGENTA" "$CYAN"; do
  [[ -n $v ]] || exit 0
done

HEADER=$(mktemp)
trap 'rm -f "$HEADER"' EXIT

cat > "$HEADER" <<EOF
### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: $ACCENT
interface_help_color: $ACCENT
interface_help_color_bright: $LIGHT_FG
hash_mismatch_panic: no

term_background: $BG
backdrop: $BG

# Terminal colors (synced from active Omarchy theme)
term_palette: $DARKER_BG;$RED;$GREEN;$YELLOW;$BLUE;$MAGENTA;$CYAN;$LIGHT_FG
term_palette_bright: $LIGHTER_BG;$BRIGHT_RED;$BRIGHT_GREEN;$BRIGHT_YELLOW;$BRIGHT_BLUE;$BRIGHT_MAGENTA;$BRIGHT_CYAN;$BRIGHT_FG

# Text colors
term_foreground: $FG
term_foreground_bright: $BRIGHT_FG
term_background_bright: $LIGHTER_BG
EOF

# /boot is mode 700 root:root on this system — nothing below this point can
# be read as this user, not even a plain -f test. Everything that touches
# $LIMINE_CONF (finding where the auto-generated boot-entry block starts,
# comparing, and writing) runs as one elevated step instead.
pkexec bash -c '
  set -euo pipefail
  limine_conf=$1
  header=$2

  [[ -f $limine_conf ]] || exit 0

  # Everything from the first boot-entry line ("/Title" syntax) onward is
  # auto-generated by limine-entry-tool / limine-snapper-sync — keep it as-is.
  entries_line=$(grep -n "^/" "$limine_conf" | head -n1 | cut -d: -f1)
  [[ -n $entries_line ]] || exit 0

  new_conf=$(mktemp)
  trap "rm -f \"\$new_conf\"" EXIT

  cat "$header" > "$new_conf"
  tail -n "+$entries_line" "$limine_conf" >> "$new_conf"

  # Only touch the real file if something actually changed.
  cmp -s "$new_conf" "$limine_conf" || cp "$new_conf" "$limine_conf"
' bash "$LIMINE_CONF" "$HEADER"
